#! /bin/bash
pdftotext -layout PitStopSummary.pdf

# Remove the blank lines.
sed -i '/^$/d' PitStopSummary.txt

# Get the timing lines.
sed -i '/^\s*[0-9].*/!d' PitStopSummary.txt

sed -i '/^.*[0-9][0-9][0-9][0-9]/d' PitStopSummary.txt
sed -i 's/  */ /' PitStopSummary.txt

perl -i.bak -e 'while (<>) { if (/^\s*(\d+).*?\s{5}.*?\w.*?\s{5}(.*)/) { print "$1$2\n"; }  }' PitStopSummary.txt
sed -i 's/  */ /g' PitStopSummary.txt

# Clean up the working files.
rm *.bak
