#! /bin/bash
pdftotext -layout Race\ History\ Chart.pdf
sed -i '/^$/d' Race\ History\ Chart.txt
grep '^\s\+[0-9]' Race\ History\ Chart.txt > tmp.txt
cat tmp.txt |tr -s ' ' > RaceHist.txt
rm Race\ History\ Chart.txt
sed -i 's/^.*\([0-9][0-9][0-9][0-9]\).*/EOL/' RaceHist.txt

rm tmp.txt
