#! /bin/bash
pdftotext -layout RaceHistoryChart.pdf
sed -i '/^$/d' RaceHistoryChart.txt
grep '^\s\+[0-9]' RaceHistoryChart.txt > tmp.txt
cat tmp.txt |tr -s ' ' > RaceHist.txt
rm RaceHistoryChart.txt
sed -i 's/^.*\([0-9][0-9][0-9][0-9]\).*/EOL/' RaceHist.txt

rm tmp.txt
