#
# Makefile
#
# $Id: //poco/1.4/Net/samples/WebSocketServer/Makefile#1 $
#
# Makefile for Poco WebSocketServer
#

include $(POCO_BASE)/build/rules/global

objects = svr

target         = svr
target_version = 1
target_libs    = PocoUtil PocoNet PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
