#! /bin/bash

# Run the replay long enough to get the msgs, no need to wait for the race to finish!
timeout 1 ./olreplay |tee output.txt

# Just keep the msgs.
sed -i '/^msg /!d' output.txt

# Strip the msg prefix.
sed -i 's/^msg //' output.txt

# Get a list of the competitor numbers (in order).
COMPETITORS=$(mktemp -t OLAP_COMP.$$.XXXXXXXXXX)
awk -F',' '{ print $4; }' output.txt |sort -n |uniq > $COMPETITORS

# Extract the msgs for each competitor in turn.
mkdir -p test
>test/all.txt
while read num; do
  grep -P '^([^,]+,)(?1)(?1)'"$num"',.*' output.txt > test/$num.txt
  cat test/$num.txt >> test/all.txt
done < $COMPETITORS

# Delete temp file(s) on exit.
function CleanUp {
  rm $COMPETITORS output.txt
  exit
}
trap CleanUp 0 SIGHUP SIGINT SIGQUIT SIGTERM

exit
